spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studenttestrecord_db 
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa: 
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client: 
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      default-zone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
      prefer-ip-address: true